# -*- coding: utf-8 -*-
"""Copy of SNR FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPpeNhKWhSY414LewGBBe_Mv910Nvu8r
"""

"""
SNR Curve — Train 2 denoising models (Baseline CAE + Transformer CAE)
on no-impairment NLOS data WITH noise augmentation, then plot SNR curve.
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy, Huber
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

# ─────────────────────────────────────────────────────────────────────────────
# 1.  CHANNEL FUNCTIONS  (exact from your training notebook)
# ─────────────────────────────────────────────────────────────────────────────
def channel_impulse_response(t, V_D, R_beta, A_eff_zeta, d_LOS, c,
                             N, K, R_betak, A_eff_zetak, d_kR, d_j1j,
                             alpha=0.02, nlos_scale=100):
    h_total = np.zeros_like(t)
    h_LOS   = np.zeros_like(t)
    h_NLOS  = np.zeros_like(t)

    tau_LOS = d_LOS / c
    idx_LOS = np.argmin(np.abs(t - tau_LOS))
    h_LOS[idx_LOS] = (V_D * R_beta * A_eff_zeta) / (d_LOS ** 2) * np.exp(-alpha * d_LOS)

    for i in range(N):
        total_len  = np.sum(d_j1j[i, :K]) + d_kR[i, K - 1]
        tau_path   = total_len / c
        idx        = np.argmin(np.abs(t - tau_path))
        scatter_loss = np.prod(R_betak[i, :K] * A_eff_zetak[i, :K])
        amp        = scatter_loss / (total_len ** 2) * np.exp(-alpha * total_len)
        h_NLOS[idx] += nlos_scale * amp

    return h_LOS + h_NLOS, h_LOS, h_NLOS


def calculate_channel_metrics(h_total, h_LOS, h_NLOS, t):
    P_LOS      = np.sum(h_LOS ** 2)
    P_NLOS     = np.sum(h_NLOS ** 2)
    eps        = 1e-30
    LGR_raw    = 10.0 * np.log10(max(P_LOS, eps) / max(P_NLOS, eps))
    LGR_compressed = 40.0 * np.tanh(LGR_raw / 40.0)
    pdp        = h_total ** 2
    t_ns       = t * 1e9
    if np.sum(pdp) > 0:
        tau_avg = np.sum(pdp * t_ns) / np.sum(pdp)
        tau_rms = np.sqrt(np.sum(pdp * (t_ns - tau_avg) ** 2) / np.sum(pdp))
    else:
        tau_rms = 0.0
    los_dominant = 1 if LGR_raw > 10.0 else 0
    return LGR_compressed, tau_rms, los_dominant

# ─────────────────────────────────────────────────────────────────────────────
# 2.  DATASET GENERATION  (no-impairment only, exact from your notebook)
# ─────────────────────────────────────────────────────────────────────────────
def generate_dataset_no_imp(num_los=500, num_nlos=500, seed=42):
    c       = 3e8
    t_full  = np.linspace(0, 5e-6, 5000)
    t_limit = 1000e-9
    idx_lim = np.argmin(np.abs(t_full - t_limit))
    t       = t_full[:idx_lim]
    rng     = np.random.default_rng(seed)

    total_samples = num_los + num_nlos
    cir_data      = np.zeros((total_samples, len(t)))
    delay_spread  = np.zeros(total_samples)
    lgr_values    = np.zeros(total_samples)
    labels        = np.zeros(total_samples)

    # LOS realizations
    los_count = 0
    while los_count < num_los:
        d_LOS       = rng.uniform(30, 70)
        N           = max(1, rng.poisson(lam=1))
        K_scatter   = 1
        R_betak     = rng.uniform(0.3, 0.7, size=(N, K_scatter))
        A_eff_zetak = rng.uniform(0.3, 0.7, size=(N, K_scatter))
        d_kR        = rng.exponential(5.0, size=(N, K_scatter)) + 1.0
        d_j1j       = rng.exponential(5.0, size=(N, K_scatter))

        h_total, h_LOS, h_NLOS = channel_impulse_response(
            t, 3.0, 0.9, 0.9, d_LOS, c,
            N, K_scatter, R_betak, A_eff_zetak, d_kR, d_j1j,
            alpha=0.02, nlos_scale=10
        )
        h_total /= max(np.max(h_total), 1e-12)
        LGR, tau_rms, los_dom = calculate_channel_metrics(h_total, h_LOS, h_NLOS, t)
        if los_dom == 1:
            cir_data[los_count]    = h_total
            delay_spread[los_count] = tau_rms
            lgr_values[los_count]  = LGR
            labels[los_count]      = 0
            los_count += 1

    # NLOS realizations
    nlos_count = 0
    while nlos_count < num_nlos:
        d_LOS       = 1000.0
        N           = max(1, rng.poisson(lam=50))
        K_scatter   = max(1, rng.poisson(lam=8))
        R_betak     = rng.uniform(0.3, 0.7, size=(N, K_scatter))
        A_eff_zetak = rng.uniform(0.3, 0.7, size=(N, K_scatter))
        d_kR        = rng.exponential(15.0, size=(N, K_scatter)) + 1.0
        d_j1j       = rng.exponential(10.0, size=(N, K_scatter))

        h_total, h_LOS, h_NLOS = channel_impulse_response(
            t, 3.0, 0.01, 0.01, d_LOS, c,
            N, K_scatter, R_betak, A_eff_zetak, d_kR, d_j1j,
            nlos_scale=100
        )
        h_total /= max(np.max(h_total), 1e-12)
        LGR, tau_rms, los_dom = calculate_channel_metrics(h_total, h_LOS, h_NLOS, t)
        if los_dom == 0:
            idx                = num_los + nlos_count
            cir_data[idx]      = h_total
            delay_spread[idx]  = tau_rms
            lgr_values[idx]    = LGR
            labels[idx]        = 1
            nlos_count += 1

    # Preprocessing
    cir_scaler      = MinMaxScaler(feature_range=(-1, 1))
    cir_data_scaled = cir_scaler.fit_transform(cir_data)
    X               = cir_data_scaled.reshape(-1, cir_data_scaled.shape[1], 1)

    lgr_scaler     = MinMaxScaler(feature_range=(-1, 1))
    Y_lgr_scaled   = lgr_scaler.fit_transform(lgr_values.reshape(-1, 1))
    Y_rec          = X.copy()
    Y_ds           = delay_spread.reshape(-1, 1)
    Y_cls          = labels.astype(int)

    X_train, X_val, \
    Yrec_train, Yrec_val, \
    Yds_train,  Yds_val,  \
    Ylgr_train, Ylgr_val, \
    Ycls_train, Ycls_val  = train_test_split(
        X, Y_rec, Y_ds, Y_lgr_scaled, Y_cls,
        test_size=0.2, random_state=42, stratify=Y_cls
    )

    return (X_train, X_val,
            Yrec_train, Yrec_val,
            Yds_train,  Yds_val,
            Ylgr_train, Ylgr_val,
            Ycls_train, Ycls_val,
            lgr_scaler, cir_scaler)

# ─────────────────────────────────────────────────────────────────────────────
# 3.  MODEL ARCHITECTURES  (exact from your training notebook)
# ─────────────────────────────────────────────────────────────────────────────
def sense_block(x, units=64, dropout=0.2, extra_layers=0):
    x = layers.Dense(units, activation="relu")(x)
    x = layers.LayerNormalization()(x)
    x = layers.Dropout(dropout)(x)
    for _ in range(extra_layers):
        x = layers.Dense(units, activation="relu")(x)
        x = layers.LayerNormalization()(x)
        x = layers.Dropout(dropout)(x)
    return x


def build_baseline_model(seq_len=1000, features=1):
    inputs = layers.Input(shape=(seq_len, features))

    # Encoder
    x = layers.Conv1D(32, 3, activation='relu', padding='same')(inputs)
    x = layers.MaxPooling1D(2)(x)
    x = layers.Conv1D(16, 3, activation='relu', padding='same')(x)
    x = layers.MaxPooling1D(2)(x)
    bottleneck = layers.Conv1D(8, 3, activation='relu', padding='same')(x)

    # Reconstruction head
    rx = layers.UpSampling1D(2)(bottleneck)
    rx = layers.Conv1D(16, 3, activation='relu', padding='same')(rx)
    rx = layers.UpSampling1D(2)(rx)
    rx = layers.Conv1D(32, 3, activation='relu', padding='same')(rx)
    reconstruction = layers.Conv1D(features, 1, activation='linear',
                                   name='reconstruction')(rx)

    # Sense block for metric heads
    flat   = layers.Flatten()(bottleneck)
    sense  = sense_block(flat, units=128, dropout=0.2)

    delay_out = layers.Dense(64, activation='relu')(sense)
    delay_out = layers.Dense(1, name='delay_output')(delay_out)

    lgr_out   = layers.Dense(64, activation='relu')(sense)
    lgr_out   = layers.Dense(1, activation='tanh', name='lgr_output')(lgr_out)

    cls_out   = layers.Dense(64, activation='relu')(sense)
    cls_out   = layers.Dense(1, activation='sigmoid', name='class_output')(cls_out)

    return Model(inputs, [delay_out, lgr_out, cls_out, reconstruction])


@tf.keras.utils.register_keras_serializable()
class TransformerBlock(layers.Layer):
    def __init__(self, d_model, num_heads, d_ff, dropout_rate=0.1, **kwargs):
        super().__init__(**kwargs)
        self.d_model      = d_model
        self.num_heads    = num_heads
        self.d_ff         = d_ff
        self.dropout_rate = dropout_rate
        self.attn         = layers.MultiHeadAttention(num_heads=num_heads, key_dim=d_model)
        self.ffn          = tf.keras.Sequential([
            layers.Dense(d_ff, activation="relu"),
            layers.Dense(d_model),
        ])
        self.norm1    = layers.LayerNormalization(epsilon=1e-6)
        self.norm2    = layers.LayerNormalization(epsilon=1e-6)
        self.dropout1 = layers.Dropout(dropout_rate)
        self.dropout2 = layers.Dropout(dropout_rate)

    def call(self, x, training=False, mask=None):
        attn_out = self.attn(x, x, x, attention_mask=mask)
        attn_out = self.dropout1(attn_out, training=training)
        out1     = self.norm1(x + attn_out)
        ffn_out  = self.ffn(out1)
        ffn_out  = self.dropout2(ffn_out, training=training)
        return self.norm2(out1 + ffn_out)

    def get_config(self):
        config = super().get_config()
        config.update({
            "d_model"     : self.d_model,
            "num_heads"   : self.num_heads,
            "d_ff"        : self.d_ff,
            "dropout_rate": self.dropout_rate,
        })
        return config


def build_transformer_model(seq_len=1000, features=1, latent_dim=64,
                            num_heads=4, d_ff=None):
    if d_ff is None:
        d_ff = 2 * latent_dim

    inputs = layers.Input(shape=(seq_len, features))

    x = layers.Conv1D(16, 5, activation="relu", padding="same")(inputs)
    x = layers.MaxPooling1D(2)(x)
    x = layers.Conv1D(32, 5, activation="relu", padding="same")(x)
    x = layers.MaxPooling1D(2)(x)
    x = layers.Dense(latent_dim)(x)
    x = TransformerBlock(d_model=latent_dim, num_heads=num_heads, d_ff=d_ff)(x)

    gap    = layers.GlobalAveragePooling1D()(x)
    gmp    = layers.GlobalMaxPooling1D()(x)
    latent = layers.Concatenate(name="latent_concat")([gap, gmp])

    ds_sense  = sense_block(latent, units=256, dropout=0.3, extra_layers=2)
    delay_out = layers.Dense(1, name="delay_output")(ds_sense)

    lgr_sense = sense_block(latent, units=128, dropout=0.3, extra_layers=2)
    lgr_out   = layers.Dense(1, name="lgr_output")(lgr_sense)

    cls_sense = sense_block(latent, units=64, dropout=0.2, extra_layers=1)
    class_out = layers.Dense(1, activation="sigmoid", name="class_output")(cls_sense)

    recon_x   = layers.TimeDistributed(layers.Dense(latent_dim, activation="relu"))(x)
    recon_x   = layers.UpSampling1D(2)(recon_x)
    recon_x   = layers.Conv1D(32, 5, activation="relu", padding="same")(recon_x)
    recon_x   = layers.UpSampling1D(2)(recon_x)
    recon_x   = layers.Conv1D(16, 5, activation="relu", padding="same")(recon_x)
    recon_out = layers.Conv1D(features, 1, activation="linear",
                              padding="same", name="reconstruction")(recon_x)

    return Model(inputs, [delay_out, lgr_out, class_out, recon_out])

# 4.  GENERATE DATASET
# ─────────────────────────────────────────────────────────────────────────────
print("Generating no-impairment dataset...")
(X_train, X_val,
 Yrec_train, Yrec_val,
 Yds_train,  Yds_val,
 Ylgr_train, Ylgr_val,
 Ycls_train, Ycls_val,
 lgr_scaler, cir_scaler) = generate_dataset_no_imp(num_los=500, num_nlos=500)

print(f"Train: {X_train.shape}  Val: {X_val.shape}")

# ─────────────────────────────────────────────────────────────────────────────
# 5.  ADD NOISE FOR TRAINING  (key change — random noise augmentation)
# ─────────────────────────────────────────────────────────────────────────────
def add_random_noise(X):
    """Add random noise with std sampled uniformly for each sample."""
    X_noisy = np.copy(X)
    for i in range(len(X)):
        std = np.random.uniform(0.01, 0.20)   # random noise level per sample
        X_noisy[i] = X[i] + np.random.normal(0, std, X[i].shape).astype(np.float32)
    return X_noisy

print("Adding noise to training data...")
X_train_noisy = add_random_noise(X_train).astype(np.float32)
X_val_noisy   = add_random_noise(X_val).astype(np.float32)

# Noisy reconstruction targets stay as clean CIRs
Ycls_train_2d = Ycls_train.reshape(-1, 1).astype("float32")
Ycls_val_2d   = Ycls_val.reshape(-1, 1).astype("float32")

# ─────────────────────────────────────────────────────────────────────────────
# 6.  BUILD AND TRAIN BASELINE MODEL
# ─────────────────────────────────────────────────────────────────────────────
print("\nBuilding and training Baseline CAE...")
baseline_model = build_baseline_model()
baseline_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss={
        "delay_output"  : Huber(delta=2.0),
        "lgr_output"    : Huber(delta=0.25),
        "class_output"  : BinaryCrossentropy(),
        "reconstruction": MeanSquaredError(),
    },
    loss_weights={
        "delay_output"  : 3.0,
        "lgr_output"    : 5.0,
        "class_output"  : 2.0,
        "reconstruction": 0.05,
    },
    metrics={
        "delay_output"  : "mae",
        "lgr_output"    : "mae",
        "class_output"  : "accuracy",
        "reconstruction": "mse",
    }
)

baseline_model.fit(
    X_train_noisy,                          # noisy input
    {
        "delay_output"  : Yds_train,
        "lgr_output"    : Ylgr_train,
        "class_output"  : Ycls_train_2d,
        "reconstruction": Yrec_train,       # clean target
    },
    validation_data=(
        X_val_noisy,
        {
            "delay_output"  : Yds_val,
            "lgr_output"    : Ylgr_val,
            "class_output"  : Ycls_val_2d,
            "reconstruction": Yrec_val,
        }
    ),
    epochs=75,
    batch_size=64,
    verbose=1,
)

# ─────────────────────────────────────────────────────────────────────────────
# 7.  BUILD AND TRAIN TRANSFORMER MODEL
# ─────────────────────────────────────────────────────────────────────────────
print("\nBuilding and training Transformer CAE...")
transformer_model = build_transformer_model()
transformer_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss={
        "delay_output"  : Huber(delta=2.0),
        "lgr_output"    : Huber(delta=0.25),
        "class_output"  : BinaryCrossentropy(),
        "reconstruction": MeanSquaredError(),
    },
    loss_weights={
        "delay_output"  : 3.0,
        "lgr_output"    : 5.0,
        "class_output"  : 2.0,
        "reconstruction": 0.05,
    },
    metrics={
        "delay_output"  : "mae",
        "lgr_output"    : "mae",
        "class_output"  : "accuracy",
        "reconstruction": "mse",
    }
)

transformer_model.fit(
    X_train_noisy,                          # noisy input
    {
        "delay_output"  : Yds_train,
        "lgr_output"    : Ylgr_train,
        "class_output"  : Ycls_train_2d,
        "reconstruction": Yrec_train,       # clean target
    },
    validation_data=(
        X_val_noisy,
        {
            "delay_output"  : Yds_val,
            "lgr_output"    : Ylgr_val,
            "class_output"  : Ycls_val_2d,
            "reconstruction": Yrec_val,
        }
    ),
    epochs=75,
    batch_size=64,
    verbose=1,
)

# ─────────────────────────────────────────────────────────────────────────────
# 8.  SNR EVALUATION
# ─────────────────────────────────────────────────────────────────────────────
def add_noise(x, std):
    return x + np.random.normal(0, std, x.shape).astype(np.float32)

def compute_snr(clean, recon):
    signal_power = np.sum(clean ** 2)
    noise_power  = np.sum((clean - recon) ** 2) + 1e-10
    return 10.0 * np.log10(signal_power / noise_power)

def get_reconstruction(model, noisy_input):
    out = model.predict(noisy_input[np.newaxis, ...], verbose=0)
    if isinstance(out, (list, tuple)):
        recon = np.array(out[3])    # reconstruction is index 3
    else:
        recon = np.array(out)
    return recon.squeeze()


noise_levels  = np.linspace(0.01, 0.20, 8)
N_EVAL        = 100
np.random.seed(0)

input_snr_avg = []
raw_snr_avg   = []
base_snr      = []
trans_snr     = []

print("\nEvaluating SNR...")
for std in noise_levels:
    input_vals, raw_vals, b_vals, t_vals = [], [], [], []

    for i in range(N_EVAL):
        clean = X_val[i]
        noisy = add_noise(clean, std)

        in_snr = compute_snr(clean.squeeze(), noisy.squeeze())
        input_vals.append(in_snr)
        raw_vals.append(in_snr)

        base_recon  = get_reconstruction(baseline_model, noisy)
        b_vals.append(compute_snr(clean.squeeze(), base_recon))

        trans_recon = get_reconstruction(transformer_model, noisy)
        t_vals.append(compute_snr(clean.squeeze(), trans_recon))

    input_snr_avg.append(np.mean(input_vals))
    raw_snr_avg.append(np.mean(raw_vals))
    base_snr.append(np.mean(b_vals))
    trans_snr.append(np.mean(t_vals))
    print(f"  noise_std={std:.3f}  input_SNR={input_snr_avg[-1]:.1f} dB  "
          f"Baseline={base_snr[-1]:.1f} dB  Transformer={trans_snr[-1]:.1f} dB")

input_snr_avg = np.array(input_snr_avg)
raw_snr_avg   = np.array(raw_snr_avg)
base_snr      = np.array(base_snr)
trans_snr     = np.array(trans_snr)

plt.figure(figsize=(8, 5))

plt.plot(input_snr_avg, base_snr,  's--', color='orange', linewidth=2, label='Baseline CAE')
plt.plot(input_snr_avg, trans_snr, '^-',  color='green',  linewidth=2, label='Transformer CAE')

plt.xlabel('Input SNR (dB)', fontsize=11, fontweight='bold')
plt.ylabel('Output SNR (dB)', fontsize=11, fontweight='bold')

plt.legend(prop={'weight': 'bold', 'size': 11})

plt.xticks(fontsize=11, fontweight='bold')
plt.yticks(fontsize=11, fontweight='bold')

plt.grid(True)
plt.tight_layout()
plt.savefig('snr_curve_no_imp.png', dpi=150)
plt.show()

print("\nSaved → snr_curve_no_imp.png")

# # ─────────────────────────────────────────────────────────────────────────────
# # 10.  PRINT RAW VALUES
# # ─────────────────────────────────────────────────────────────────────────────
# print("\n===== RAW SNR VALUES =====")
# print(f"{'Input SNR':<15} {'Raw Ref':<12} {'Baseline':<12} {'Transformer':<12}")
# for i in range(len(input_snr_avg)):
#     print(f"{input_snr_avg[i]:<15.2f} {raw_snr_avg[i]:<12.2f} "
#           f"{base_snr[i]:<12.2f} {trans_snr[i]:<12.2f}")
print("\n===== SNR VALUES =====")
print(f"{'Input SNR':<15} {'Baseline':<12} {'Transformer':<12}")

for i in range(len(input_snr_avg)):
    print(f"{input_snr_avg[i]:<15.2f} "
          f"{base_snr[i]:<12.2f} {trans_snr[i]:<12.2f}")



"""ANOTHER VARIATION OF CODE"""

# ─────────────────────────────────────────────────────────────────────────────
# 8.  SNR EVALUATION (FINAL — FULLY CORRECT)
# ─────────────────────────────────────────────────────────────────────────────

def add_noise_snr(clean, snr_db):
    signal_power = np.mean(clean**2)
    snr_linear = 10**(snr_db / 10)
    noise_power = signal_power / snr_linear
    noise = np.random.normal(0, np.sqrt(noise_power), clean.shape)
    return clean + noise


def compute_snr(clean, recon):
    signal_power = np.sum(clean ** 2)
    noise_power  = np.sum((clean - recon) ** 2) + 1e-10
    return 10.0 * np.log10(signal_power / noise_power)


def get_reconstruction(model, noisy_scaled):
    out = model.predict(noisy_scaled[np.newaxis, ...], verbose=0)
    if isinstance(out, (list, tuple)):
        recon = np.array(out[3])   # reconstruction output
    else:
        recon = np.array(out)
    return recon.squeeze()


# ✅ SNR levels
snr_levels = np.arange(-5, 21, 5)

N_EVAL = 100
np.random.seed(0)

base_snr  = []
trans_snr = []

print("\nEvaluating SNR...")

for snr_db in snr_levels:
    b_vals, t_vals = [], []

    for i in range(N_EVAL):

        # ───────────── STEP 1: Get scaled signal (model domain)
        clean_scaled = X_val[i]              # (seq_len, 1)

        # ───────────── STEP 2: Convert to real domain
        clean_real = cir_scaler.inverse_transform(
            clean_scaled.reshape(1, -1)
        )[0]                                 # (seq_len,)

        # ───────────── STEP 3: Add noise in real domain
        noisy_real = add_noise_snr(clean_real, snr_db)  # (seq_len,)

        # ───────────── STEP 4: Convert back to scaled for model
        noisy_scaled = cir_scaler.transform(
            noisy_real.reshape(1, -1)
        )[0].reshape(-1, 1)                  # (seq_len, 1)

        # ───────────── STEP 5: Baseline reconstruction
        base_recon_scaled = get_reconstruction(baseline_model, noisy_scaled)

        # Convert to real domain
        base_recon_real = cir_scaler.inverse_transform(
            base_recon_scaled.reshape(1, -1)
        )[0]

        b_vals.append(compute_snr(clean_real, base_recon_real))

        # ───────────── STEP 6: Transformer reconstruction
        trans_recon_scaled = get_reconstruction(transformer_model, noisy_scaled)

        # Convert to real domain
        trans_recon_real = cir_scaler.inverse_transform(
            trans_recon_scaled.reshape(1, -1)
        )[0]

        t_vals.append(compute_snr(clean_real, trans_recon_real))

    base_snr.append(np.mean(b_vals))
    trans_snr.append(np.mean(t_vals))

    print(f"  Input_SNR={snr_db:.1f} dB  "
          f"Baseline={base_snr[-1]:.2f} dB  "
          f"Transformer={trans_snr[-1]:.2f} dB")


# Convert to numpy arrays
snr_levels = np.array(snr_levels)
base_snr   = np.array(base_snr)
trans_snr  = np.array(trans_snr)

# ─────────────────────────────────────────────────────────────────────────────
# 9.  PLOT (Corrected — SNR-based)
# ─────────────────────────────────────────────────────────────────────────────

plt.figure(figsize=(8, 5))

# Ideal reference line
plt.plot(snr_levels, snr_levels, 'k--', linewidth=2, label='Ideal (y = x)')

# Model curves
plt.plot(snr_levels, base_snr,  's--', linewidth=2, label='Baseline CAE')
plt.plot(snr_levels, trans_snr, '^-',  linewidth=2, label='Transformer CAE')

# Labels (bold, size 11)
plt.xlabel('Input SNR (dB)', fontsize=11, fontweight='bold')
plt.ylabel('Output SNR (dB)', fontsize=11, fontweight='bold')

# Tick labels bold
plt.xticks(fontsize=11, fontweight='bold')
plt.yticks(fontsize=11, fontweight='bold')

# Legend bold
plt.legend(prop={'weight': 'bold', 'size': 11})

# Grid and layout
plt.grid(True)
plt.tight_layout()

# Save
plt.savefig('snr_curve_no_imp.png', dpi=150)
plt.show()

print("\nSaved → snr_curve_no_imp.png")



import numpy as np
import matplotlib.pyplot as plt

# ---- Exact values from your table ----
input_snr = np.array([40.00, 28.59, 23.81, 20.76, 18.48, 16.72, 15.20, 13.97])
baseline  = np.array([28.82, 28.76, 28.71, 28.63, 28.49, 27.82, 27.24, 26.32])
transform = np.array([32.39, 30.92, 29.98, 29.41, 29.18, 28.74, 28.13, 27.30])

# ---- Sort for proper curve plotting ----
idx = np.argsort(input_snr)
input_snr = input_snr[idx]
baseline  = baseline[idx]
transform = transform[idx]

# ---- Plot ----
plt.figure(figsize=(8, 5))

plt.plot(input_snr, baseline,  's--', color='orange', linewidth=2, label='Baseline CAE')
plt.plot(input_snr, transform, '^-',  color='green',  linewidth=2, label='Transformer CAE')

# ---- Labels ----
plt.xlabel('Input SNR (dB)', fontsize=11, fontweight='bold')
plt.ylabel('Output SNR (dB)', fontsize=11, fontweight='bold')

# ---- Remove padding ----
plt.margins(x=0, y=0)  # key line

# Optional: hard limits (extra strict, if reviewer zooms in like a detective)
plt.xlim(input_snr.min(), input_snr.max())
plt.ylim(min(baseline.min(), transform.min()),
         max(baseline.max(), transform.max()))

# ---- Styling ----
plt.legend(prop={'weight': 'bold', 'size': 11})
plt.xticks(fontsize=11, fontweight='bold')
plt.yticks(fontsize=11, fontweight='bold')
plt.grid(True)

plt.tight_layout()
plt.savefig('snr_curve_no_imp.png', dpi=150, bbox_inches='tight')
plt.show()